#This is the SavageDeathChest config file

# Localization language
language: en-US

# Storage Type ( sqlite | yaml )
storage-type: sqlite


# Note: use only one enabled/disabled list, and comment out or remove the other
# enabled worlds list (use this list for a default-deny world policy)

#enabled-worlds:
#  - enabled_world1
#  - enabled_world2


# disabled worlds list (use this list for a default-allow world policy)

disabled-worlds:
  - disabled_world1
  - disabled_world2

# Require players to have a chest in their inventory
require-chest: false

# Uncomment the name of protection plugins that should be ignored when 
# placing a death chest. Players may not have access to their chests in
# areas protected by these plugins if they are ignored.
# NOTE: Listed values must match plugin name exactly, including case.
ignored-plugins:
#  - GriefPrevention
#  - PreciousStones
#  - Towny
#  - WorldGuard

# Protect chests from other players
chest-protection: true

# prevent placing items in death chests
prevent-item-placement: true

# Distance from death location to search for a valid chest location
# NOTE: This checks exponentially more locations for each increase in distance
# For this reason, it is not recommended to set this value too high.
search-distance: 5

# Place sign on death chests
chest-signs: true

# Time in minutes before death chests expire. Set to 0 (zero) to disable chest expiration.
expire-time: 60

# Drop items that don't fit in death chest
allow-drops: true

# Allow quick-looting of chests with sneak-punch
quick-loot: true

# Allow killers to loot chests
killer-looting: false

# Automatically remove empty chests on closing
remove-empty: true

# Use sound effects
sound-effects: true

# List of blocks that can be replaced by a chest
replaceable-blocks:
  - AIR
  - LONG_GRASS
  - SNOW
  - VINE
  - WATER_LILY
  - WATER
  - STATIONARY_WATER
  - LAVA
  - STATIONARY_LAVA
